### ISSUE TITLE
name 'pio' is not defined in MAYA.notebook

### ISSUE THREAD

**Issue by MachineGUN001** [IsrC11/MAYA#1]
hi, @IsrC11 

thank for your cool work.

in the notebook, MAYA.ipynb, there are some errors as below, 

--> [144](vscode-notebook-cell:?execution_count=8&line=144)       pio.write_image(fig_pca, 'fig_PCA_MACCS_high_res.png', scale=10, width=1200, height=900)
    [146](vscode-notebook-cell:?execution_count=8&line=146) if t_SNE is True:
    [147](vscode-notebook-cell:?execution_count=8&line=147)         data_tsne_MACCS = matrix_MACCS.copy()

NameError: name 'pio' is not defined

please fix it up? thanks,

best,

**Comment by IsrC11** [comment]
Hi, I greatly appreciate your comment. The MAYA.ipynb is currently running correctly. Thank you.

**Comment by MachineGUN001** [comment]
@IsrC11 thanks a lot!
